"""add gigscore to users

Revision ID: aa9a6c8a73a6
Revises: ae240a6e9a7e
Create Date: 2026-04-04 17:39:43.067865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9a6c8a73a6'
down_revision: Union[str, None] = 'ae240a6e9a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gigscore', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gigscore')
    # ### end Alembic commands ###
