"""add trigger_events table

Revision ID: ae240a6e9a7e
Revises: 00c5fa6e1843
Create Date: 2026-04-04 16:05:03.069512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae240a6e9a7e'
down_revision: Union[str, None] = '00c5fa6e1843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
